# See example at https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
# This is being picked up automatically (by convention) by the github action
# defined in .github/workflows/golanci-lint.yml by convention
linters:
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

